# Generated by Django 4.0.3 on 2022-07-22 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_followup'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='converted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
